name: Deploy to Staging GitHub Pages

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3

      - name: Deploy to Staging Site Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: richardigwegbu1/richard_portfolio_site_staging
          publish_dir: .
          github_token: ${{ secrets.GITHUB_TOKEN }}

